### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by evolution-ant** [pynecone-io/pcweb#5]
python3.7
pc run then i get this error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pc", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynecone/pc.py", line 78, in run
    app = utils.get_app()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynecone/utils.py", line 365, in get_app
    app = __import__(module, fromlist=(constants.APP_VAR,))
  File "/Users/gaga/Work/demo/pcweb/pcweb/pcweb.py", line 9, in <module>
    from pcweb.pages import routes
  File "/Users/gaga/Work/demo/pcweb/pcweb/pages/__init__.py", line 1, in <module>
    from pcweb.route import Route
  File "/Users/gaga/Work/demo/pcweb/pcweb/route.py", line 10, in <module>
    class Route(Base):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 263, in _eval_type
    return t._evaluate(globalns, localns)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by picklelo** [comment]
Ah I think this app you need Python 3.9+ to run - we use some newer Python features.

The core repo we make sure to keep compatible with Python 3.7.
